var STROKE_BASE_INFO = {
  人: {
    count: 2,
    strokes: ["撇（左斜）", "捺（右斜）"],
    tip: "像一个人站立，两脚分开",
  },
  山: {
    count: 3,
    strokes: ["竖（中间）", "竖折（左）", "竖（右）"],
    tip: "像三座山峰并排",
  },
  水: {
    count: 4,
    strokes: ["竖钩", "横撇", "撇", "点"],
    tip: "像水往下流的样子",
  },
  木: {
    count: 4,
    strokes: ["横", "竖", "撇", "捺"],
    tip: "像一棵树，有树干树枝",
  },
  日: {
    count: 4,
    strokes: ["竖", "横折", "横", "横"],
    tip: "像太阳形状，四四方方",
  },
  月: {
    count: 4,
    strokes: ["撇", "横折钩", "横", "横"],
    tip: "像弯弯的月亮",
  },
  火: {
    count: 4,
    strokes: ["点", "撇", "撇", "捺"],
    tip: "像火焰向上燃烧",
  },
  口: {
    count: 3,
    strokes: ["竖", "横折", "横"],
    tip: "像嘴巴张开的形状",
  },
  手: {
    count: 4,
    strokes: ["横", "横", "横", "竖钩"],
    tip: "像手的形状",
  },
  心: {
    count: 4,
    strokes: ["点", "卧钩", "点", "点"],
    tip: "像心脏的形状",
  },
  大: {
    count: 3,
    strokes: ["横", "撇", "捺"],
    tip: "像一个人张开双臂",
  },
  小: {
    count: 3,
    strokes: ["竖钩", "点", "点"],
    tip: "两点在旁边，中间一竖",
  },
};

var STROKE_CHAR_GROUPS = {
  一年级: [
    { char: "人", pinyin: "rén" },
    { char: "大", pinyin: "dà" },
    { char: "山", pinyin: "shān" },
    { char: "水", pinyin: "shuǐ" },
    { char: "火", pinyin: "huǒ" },
    { char: "木", pinyin: "mù" },
    { char: "口", pinyin: "kǒu" },
    { char: "手", pinyin: "shǒu" },
    { char: "花", pinyin: "huā" },
    { char: "草", pinyin: "cǎo" },
    { char: "天", pinyin: "tiān" },
    { char: "地", pinyin: "dì" },
    { char: "云", pinyin: "yún" },
    { char: "风", pinyin: "fēng" },
    { char: "雨", pinyin: "yǔ" },
    { char: "雪", pinyin: "xuě" },
    { char: "星", pinyin: "xīng" },
    { char: "月", pinyin: "yuè" },
    { char: "日", pinyin: "rì" },
    { char: "石", pinyin: "shí" },
  ],
  二年级: [
    { char: "心", pinyin: "xīn" },
    { char: "目", pinyin: "mù" },
    { char: "耳", pinyin: "ěr" },
    { char: "足", pinyin: "zú" },
    { char: "鸟", pinyin: "niǎo" },
    { char: "鱼", pinyin: "yú" },
    { char: "马", pinyin: "mǎ" },
    { char: "牛", pinyin: "niú" },
    { char: "羊", pinyin: "yáng" },
    { char: "鸡", pinyin: "jī" },
    { char: "鸭", pinyin: "yā" },
    { char: "树", pinyin: "shù" },
    { char: "叶", pinyin: "yè" },
    { char: "果", pinyin: "guǒ" },
    { char: "桃", pinyin: "táo" },
    { char: "柳", pinyin: "liǔ" },
    { char: "竹", pinyin: "zhú" },
    { char: "松", pinyin: "sōng" },
  ],
  三年级: [
    { char: "力", pinyin: "lì" },
    { char: "土", pinyin: "tǔ" },
    { char: "王", pinyin: "wáng" },
    { char: "田", pinyin: "tián" },
    { char: "女", pinyin: "nǚ" },
    { char: "子", pinyin: "zǐ" },
    { char: "海", pinyin: "hǎi" },
    { char: "湖", pinyin: "hú" },
    { char: "江", pinyin: "jiāng" },
    { char: "河", pinyin: "hé" },
    { char: "溪", pinyin: "xī" },
    { char: "泉", pinyin: "quán" },
    { char: "峰", pinyin: "fēng" },
    { char: "岭", pinyin: "lǐng" },
    { char: "峡", pinyin: "xiá" },
    { char: "岸", pinyin: "àn" },
    { char: "岛", pinyin: "dǎo" },
    { char: "勤", pinyin: "qín" },
    { char: "善", pinyin: "shàn" },
    { char: "诚", pinyin: "chéng" },
  ],
  四年级: [
    { char: "温", pinyin: "wēn" },
    { char: "暖", pinyin: "nuǎn" },
    { char: "凉", pinyin: "liáng" },
    { char: "寒", pinyin: "hán" },
    { char: "宽", pinyin: "kuān" },
    { char: "窄", pinyin: "zhǎi" },
    { char: "厚", pinyin: "hòu" },
    { char: "薄", pinyin: "bó" },
    { char: "喜", pinyin: "xǐ" },
    { char: "悦", pinyin: "yuè" },
    { char: "悲", pinyin: "bēi" },
    { char: "伤", pinyin: "shāng" },
    { char: "惧", pinyin: "jù" },
    { char: "怕", pinyin: "pà" },
    { char: "坚", pinyin: "jiān" },
    { char: "毅", pinyin: "yì" },
    { char: "恒", pinyin: "héng" },
    { char: "持", pinyin: "chí" },
    { char: "谦", pinyin: "qiān" },
    { char: "傲", pinyin: "ào" },
  ],
  五年级: [
    { char: "智", pinyin: "zhì" },
    { char: "慧", pinyin: "huì" },
    { char: "责", pinyin: "zé" },
    { char: "任", pinyin: "rèn" },
    { char: "信", pinyin: "xìn" },
    { char: "仰", pinyin: "yǎng" },
    { char: "望", pinyin: "wàng" },
    { char: "梦", pinyin: "mèng" },
    { char: "想", pinyin: "xiǎng" },
    { char: "念", pinyin: "niàn" },
    { char: "愿", pinyin: "yuàn" },
    { char: "志", pinyin: "zhì" },
    { char: "向", pinyin: "xiàng" },
    { char: "往", pinyin: "wǎng" },
    { char: "扬", pinyin: "yáng" },
    { char: "摇", pinyin: "yáo" },
    { char: "摆", pinyin: "bǎi" },
    { char: "飘", pinyin: "piāo" },
    { char: "荡", pinyin: "dàng" },
    { char: "浮", pinyin: "fú" },
  ],
  六年级: [
    { char: "哲", pinyin: "zhé" },
    { char: "思", pinyin: "sī" },
    { char: "悟", pinyin: "wù" },
    { char: "解", pinyin: "jiě" },
    { char: "释", pinyin: "shì" },
    { char: "疑", pinyin: "yí" },
    { char: "惑", pinyin: "huò" },
    { char: "辨", pinyin: "biàn" },
    { char: "析", pinyin: "xī" },
    { char: "宇", pinyin: "yǔ" },
    { char: "宙", pinyin: "zhòu" },
    { char: "穹", pinyin: "qióng" },
    { char: "瀚", pinyin: "hàn" },
    { char: "茫", pinyin: "máng" },
    { char: "渺", pinyin: "miǎo" },
    { char: "巍", pinyin: "wēi" },
    { char: "峨", pinyin: "é" },
    { char: "巅", pinyin: "diān" },
    { char: "鹏", pinyin: "péng" },
    { char: "德", pinyin: "dé" },
  ],
};

function makeStrokeChar(item) {
  var info = STROKE_BASE_INFO[item.char] || {};
  return {
    char: item.char,
    pinyin: item.pinyin,
    count: info.count || 0,
    strokes: info.strokes ? info.strokes.slice() : [],
    tip: info.tip || "按正确笔顺描写这个字",
  };
}

var STROKE_GRADES = Object.keys(STROKE_CHAR_GROUPS);
var STROKE_DATA_GROUPS = STROKE_GRADES.reduce(function (groups, grade) {
  groups[grade] = STROKE_CHAR_GROUPS[grade].map(makeStrokeChar);
  return groups;
}, {});
var STROKE_DATA = STROKE_GRADES.reduce(function (items, grade) {
  return items.concat(STROKE_DATA_GROUPS[grade]);
}, []);
