let dom = {};
export function initDomCache() {
    dom = {
        searchInput: document.getElementById('searchInput'),
        sortSelect: document.getElementById('sortSelect'),
        groupList: document.getElementById('groupList'),
        colorGrid: document.getElementById('colorGrid'),
        gradientContent: document.getElementById('gradientContent'),
        schemeContent: document.getElementById('schemeContent'),
        batchBar: document.getElementById('batchBar'),
        batchBarText: document.getElementById('batchBarText'),
        multiSelectBtn: document.getElementById('multiSelectBtn'),
        addGroupInputWrap: document.getElementById('addGroupInputWrap'),
        newGroupName: document.getElementById('newGroupName'),
        confirmAddGroup: document.getElementById('confirmAddGroup'),
        colorModal: document.getElementById('colorModal'),
        modalTitle: document.getElementById('modalTitle'),
        colorName: document.getElementById('colorName'),
        colorPicker: document.getElementById('colorPicker'),
        colorHex: document.getElementById('colorHex'),
        modalGroupSelect: document.getElementById('modalGroupSelect'),
        saveColorBtn: document.getElementById('saveColorBtn'),
        closeModalBtn: document.getElementById('closeModalBtn'),
        confirmModal: document.getElementById('confirmModal'),
        confirmMessage: document.getElementById('confirmMessage'),
        confirmOkBtn: document.getElementById('confirmOkBtn'),
        confirmCancelBtn: document.getElementById('confirmCancelBtn'),
        helpModal: document.getElementById('helpModal'),
        helpBtn: document.getElementById('helpBtn'),
        closeHelpBtn: document.getElementById('closeHelpBtn'),
        imagePickModal: document.getElementById('imagePickModal'),
        imagePreviewWrap: document.getElementById('imagePreviewWrap'),
        imagePreviewImg: document.getElementById('imagePreviewImg'),
        noImageText: document.getElementById('noImageText'),
        extractCountSlider: document.getElementById('extractCountSlider'),
        extractCountBadge: document.getElementById('extractCountBadge'),
        reExtractBtn: document.getElementById('reExtractBtn'),
        extractedColorsGrid: document.getElementById('extractedColorsGrid'),
        selectedCountText: document.getElementById('selectedCountText'),
        selectAllExtractedBtn: document.getElementById('selectAllExtractedBtn'),
        deselectAllExtractedBtn: document.getElementById('deselectAllExtractedBtn'),
        addExtractedColorsBtn: document.getElementById('addExtractedColorsBtn'),
        closeImagePickModalBtn: document.getElementById('closeImagePickModalBtn'),
        shadeExportModal: document.getElementById('shadeExportModal'),
        shadeExportCode: document.getElementById('shadeExportCode'),
        copyShadeCodeBtn: document.getElementById('copyShadeCodeBtn'),
        closeShadeExportBtn: document.getElementById('closeShadeExportBtn'),
        importModeModal: document.getElementById('importModeModal'),
        importMergeBtn: document.getElementById('importMergeBtn'),
        importReplaceBtn: document.getElementById('importReplaceBtn'),
        importConfirmBtn: document.getElementById('importConfirmBtn'),
        importCancelBtn: document.getElementById('importCancelBtn'),
        importFile: document.getElementById('importFile'),
        exportBtn: document.getElementById('exportBtn'),
        addColorBtn: document.getElementById('addColorBtn'),
        addGroupBtn: document.getElementById('addGroupBtn'),
        batchSelectAllBtn: document.getElementById('batchSelectAllBtn'),
        batchDeleteBtn: document.getElementById('batchDeleteBtn'),
        batchCancelBtn: document.getElementById('batchCancelBtn'),
        imagePickBtn: document.getElementById('imagePickBtn'),
        imagePickFile: document.getElementById('imagePickFile'),
    };
}
export function getDom() { return dom; }